```{r}
library(dplyr)
library(magrittr)

```

```{r}
band_members %>% View()
band_instruments %>% View()

join1 = band_members %>% inner_join(band_instruments)

join2= band_instruments %>% left_join(band_instruments)

join3= band_instruments %>% right_join(band_instruments)

join4= band_instruments %>% full_join(band_instruments2, by = c("name"="artist"))

join5= band_instruments %>% anti_join(band_instruments)
```

do.call
combinar vectores
```{r}
vectors = list(c(1,2,3), c(4,5,6),c(7,8,9))
combined_matrix = do.call(rbind,vectors)
combined_matrix

```
Aplicando operaciones
a varios dataframes

```{r}
data_frames = list(data.frame(a = 1:3), data.frame(a = 4:6), data.frame(a = 7:9))

mean_results = do.call(rbind, lapply(data_frames, function(df) data.frame(mean = mean(df$a))))
mean_results

```
dinamismo 

```{r}
vectors <- list(c(1,2,3),c(4,5,6))
if (length(vectors)==2){
  result <- do.call("+", vectors)
}else if (length(vectors)==3){
  result <- do.call("*", vectors)
}
result
```

otros

```{r}
#promedio

numbers = list(1:5)
do.call(mean,numbers)

#ordenar
do.call(sort,numbers)


#grafico
un=unlist(numbers)
do.call(plot,list(x = un, y = un))

#regresion
mod= do.call(lm,list(y ~.,data = data.frame(x = un, y = un)))
mod$coefficientes
```

